.ORIG x3000
AND R0,R0, #0 ;; R0, WILL HOLD THE FIRST NUMBER
BRn #14      ;; NO NEGATIVE INTEGER IN THIS PROGRAM
AND R1,R1, #0 ;; R1, WILL HOLD THE SECOND NUMBER
LDI R0, FIRST
LDI R1, SECOND 
BRnz #10       ;; CAN'T DIVISE BY ZERO AND ALSO NO NEGATIVE INTEGER IN THIS PROGRAM
AND R3,R3, #0 ;; R3 WILL HOLD THE RESULT
AND R4,R4, #0 ;; R4, WILL HOLD THE REMAINING
AND R5, R5, #0 ;; HOLD THE TEMP RESULT
NOT R2, R1    ;; CHANGE SIGN OF THE SECOND NUMBER
ADD R2, R2, #1 ;;
ADD R5, R0, R2 ;; FIRST NUMBER - SECOND NUMBER
BRn #3       ;;IF THE RESULT IS NEGATIVE--> HALT
;;ADD R0,R5,#0   ;; ELSE PUT THE RESULT OF R3 BACK INTO R0
ADD R3, R3, #1 ;; INCREASE THE COUNTER
ADD R5, R5,R2 ;; FIRST - SECOND AGAIN
BRnzp #-4     ;; UNCONDITIONAL BRANCH
HALT
FIRST .FILL x3100
SECOND .FILL x3101
.END
